language: node_js
node_js:
- '4.0'
- '4'
- '5'
- '6.0'
- '6'
- '7'
sudo: required
before_install:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
- echo "deb [ arch=amd64 ] http://repo.mongodb.com/apt/ubuntu precise/mongodb-enterprise/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-enterprise.list
- sudo apt-get update
- sudo apt-get install -y mongodb-enterprise-server
script: npm run lint && npm test
after_success:
- cat coverage/lcov.info | node_modules/.bin/coveralls
notifications:
  email: false
  slack:
    secure: dZL3mHFwaqFP8JD19pe5iodurWVwSd3YuDBfMcwdypR59h1zhMM/A8MU5Yv6P5tArDCbvumewrSah9NghFEVJS5KbuGEWt+i33X8vDYMzxR9yhEuqNUKWCJSsQtkLuzdtNToeqfWf4ozRrTL8S3f7EVj7QXda/p7SF9iW7WKpogLwVK6evxHN7aUJTbyW02syRwzeqF9FGptxfulZbKTlRj0At7i48/+wtDGMLsOx887HsdWpVXds47wcEmL9VBYa6SoxqHV/pkPl2PS031lOyOST2Hjg+bfeQmhxTjdyzYi3uYXcqoEpLMim2iPknEUxmZPspzsctzegk3eJcP5jWKUT4tdx36KIAW6vJNBNG7ybG7oG9Dk9HrJswDyv28fShF8XYb2JYgtXdG1pp5kwGVtY67p00/Zwcr1l6kKzavQJKTsWjakA2mA+4Ix7kUHEVuHEIdFHrd32J1y4Z9P7OJHZ9HLrXzHh0rBcN5lRi4tSrw60hg5A6QlWxOeYRJEucB4C03yhU38eiSKwXAyJSMJ5hujGP7bVPjBkYZjxO5tLvINrO/1rMN9FE/DLHLY3mRK1nIGgFI/axOQ/oarLmdY7aFezE+GoiiRrD5vdYEIvy5ebemjHsWMlIsGQOHaI05a2S3O/zh3GCibZu1QBHiCjM/PSBhISOK6W26q7DQ=
branches:
  only:
  - master
  - develop
